wordpress:
  host: my-load-balancer-2054635803.eu-west-3.elb.amazonaws.com
  replicas: 2
  image:
    repository: barnz/wordpress-filrouge
    tag: 1.3
  imagePullPolicy: Always
  wp_db_host: mariadb-service
  hpa:
    min: 2
    max: 5
    cpu: 50
mariadb:
  replicas: 1
  image:
    repository: mariadb
    tag: 11.1
  imagePullPolicy: IfNotPresent
  mysql_root_password: root
  mysql_database: wordpress
  mysql_user: wordpress
  mysql_password: wordpress
  
