wordpress:
  host: filrouge-test.kawaz.cloudns.ph
  replicas: 3
  image:
    repository: jaysse/pipeline-serviceweb
    tag: latest
  imagePullPolicy: Always
  wp_db_host: mariadb-service
  hpa:
    min: 2
    max: 4
    cpu: 50
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - wordpress
          topologyKey: "kubernetes.io/hostname"

mariadb:
  replicas: 1
  image:
    repository: mariadb
    tag: 11.1
  imagePullPolicy: IfNotPresent
  mysql_root_password: root
  mysql_database: wordpress
  mysql_user: wordpress
  mysql_password: wordpress
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - mariadb
          topologyKey: "kubernetes.io/hostname"
